version: '3.1'

volumes:
  pgdata:


services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    ports:
      - 3567:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - 6678:6379
  bybit-collector:
    image: bybit-collector
    container_name: bybit-collector
    restart: always
    build: .
    volumes:
        - './configs:/configs'
        - './logs:/logs'
    ports: 
        - "4257:4257"
  bybit-bot:
    image: bybit-bot
    container_name: bybit-bot
    restart: always
    build: .
    volumes:
        - './configs:/configs'
        - './logs:/logs'
    ports: 
        - "3219:3219"

networks:
  default:
    name: "my-bridge-network"
    external: true
